name: monee
description: Finance Management App Friendly and Easy Experiment
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  bloc: ^9.0.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.2.0
  equatable: ^2.0.7
  fl_chart: ^1.1.1
  flash: ^3.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  go_router: ^17.0.0
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  uuid: ^4.5.2

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: KantumruyPro
      fonts:
        - asset: assets/fonts/KantumruyPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/KantumruyPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/KantumruyPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/KantumruyPro-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
